# MySQL連線設定
spring.application.name=pratice
spring.datasource.url=jdbc:mysql://localhost:3306/springboot?useSSL=false&serverTimezone=Asia/Taipei&characterEncoding=utf8
spring.datasource.username=ray
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# JPA設定
spring.jpa.hibernate.ddl-auto=update
# 是否在 console 印出 SQL 指令並對其格式化
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true