spring.application.name=demo
# MySQL連線設定
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/midterm?useSSL=false&serverTimezone=Asia/Taipei&characterEncoding=utf8
spring.datasource.username=ray
spring.datasource.password=root
